---
- name: Ensure first wildfly is deployed and running
  import_playbook: ../../playbooks/playbook.yml
  vars:
    id: 1
    wildfly_node_id: "wildfly-{{ id }}"
    wildfly_instance_name: "wildfly-{{ id }}"
    wildfly_service_name: "wildfly-{{ id }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_install_workdir: "/opt/wildfly-{{ id }}/"
    wildfly_port_range_offset: "{{ 100 * (id - 1) | int }}"
    jdbc_drivers: []

- name: Ensure second wildfly is deployed and running
  import_playbook: ../../playbooks/playbook.yml
  vars:
    id: 2
    wildfly_node_id: "wildfly-{{ id }}"
    wildfly_instance_name: "wildfly-{{ id }}"
    wildfly_service_name: "wildfly-{{ id }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_install_workdir: "/opt/wildfly-{{ id }}/"
    wildfly_port_range_offset: "{{ 100 * (id - 1) | int }}"
    jboss_cli_controller_port: 10090
    jdbc_drivers: []

- name: Ensure third wildfly is deployed and running
  import_playbook: ../../playbooks/playbook.yml
  vars:
    id: 3
    wildfly_node_id: "wildfly-{{ id }}"
    wildfly_instance_name: "wildfly-{{ id }}"
    wildfly_service_name: "wildfly-{{ id }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_install_workdir: "/opt/wildfly-{{ id }}/"
    wildfly_port_range_offset: "{{ 100 * (id - 1) | int }}"
    jboss_cli_controller_port: 10190
    jdbc_drivers: []

- name: Ensure third wildfly is deployed and running
  hosts: all
  vars:
    id: 3
    wildfly_node_id: "wildfly-{{ id }}"
    wildfly_instance_name: "wildfly-{{ id }}"
    wildfly_service_name: "wildfly-{{ id }}"
    wildfly_config_base: standalone-ha.xml
    wildfly_install_workdir: "/opt/wildfly-{{ id }}/"
    wildfly_port_range_offset: "{{ 100 * (id - 1) | int }}"
    jboss_cli_controller_port: 10190
    path_to_app: /tmp/info.war
    download_app_url: 'https://drive.google.com/uc?export=download&id=13K7RCqccgH4zAU1RfOjYMehNaHB0A3Iq'
  roles:
    - middleware_automation.wildfly.wildfly_install
    - middleware_automation.wildfly.wildfly_systemd
  post_tasks:
    - name: "Deploy webapp if test enabled"
      when:
        - not eap_enable is defined or not eap_enable
      block:
        - name: "Deploy webapp"
          ansible.builtin.get_url:
            url: "{{ download_app_url }}"
            dest: "{{ path_to_app }}"

        - name: "Check that webapp is available"
          ansible.builtin.include_role:
            name: wildfly_utils
            tasks_from: jboss_cli.yml
          vars:
            jboss_home: "{{ wildfly_home }}"
            jboss_cli_query: "'deploy --force {{ path_to_app }}'"
