---
- name: "Check if {{ wildfly_instance_name }} service is running"
  ansible.builtin.systemd:
    name: "{{ wildfly_instance_name }}"
  register: service_status

- name: "Get {{ wildfly_instance_name }} process ID"
  ansible.builtin.command: "pgrep -f {{ wildfly_instance_name }}"
  register: wildfly_pid
  ignore_errors: yes
  when: service_status.status.ActiveState == "active"

- name: "Read content of the PID file"
  ansible.builtin.slurp:
    src: "{{ wildfly_validation_systemd_pidfile }}"
  register: pid_file_content
  when: service_status.status.ActiveState == "active"

- name: "Compare {{ wildfly_instance_name }} process ID with PID file content"
  ansible.builtin.assert:
    that:
      - wildfly_pid.stdout | int == pid_file_content.content | b64decode | int
    msg: "WildFly process ID does not match PID file content"
  when: service_status.status.ActiveState == "active"
