---
- name: "Verify that PID file has been created."
  ansible.builtin.assert:
    that:
      - wildfly_validation_systemd_pidfile is exists
    quiet: true
    fail_msg: "PID file {{ wildfly_validation_systemd_pidfile }} has not been created."
  when:
    - wildfly_validation_systemd_pidfile is defined and wildfly_validation_systemd_pidfile | length > 0

- name: "Read content of the PID file"
  ansible.builtin.slurp:
    src: "{{ wildfly_validation_systemd_pidfile }}"
  register: pid_file_content
  when: service_status.status.ActiveState == "active"

- name: "Compare {{ wildfly_instance_name }} process ID with PID file content"
  ansible.builtin.assert:
    that:
      - wildfly_pid.stdout | int == pid_file_content.content | b64decode | int
    msg: "WildFly process ID does not match PID file content"
  when: service_status.status.ActiveState == "active"
