---
- name: "Populate services list"
  ansible.builtin.service_facts:

- name: "Check if service is running"
  ansible.builtin.assert:
    that:
      - ansible_facts is defined
      - ansible_facts.services is defined
      - ansible_facts.services["{{ wildfly_service_name }}.service"] is defined
      - ansible_facts.services["{{ wildfly_service_name }}.service"]['state'] is defined
      - ansible_facts.services["{{ wildfly_service_name }}.service"]['state'] == 'running'
      - ansible_facts.services["{{ wildfly_service_name }}.service"]['status'] == 'enabled'
    quiet: true
    fail_msg: "Systemd service {{ wildfly_service_name }} is not the expected state."
  when:
    - wildfly_service_name is defined
