---
- import_playbook: ../../playbooks/validate.yml

- name: Validation
  hosts: all
  tasks:
    - name: Verify we are running on requested jvm
      ansible.builtin.shell: |
        ps -ef | grep /etc/alternatives/jre_11/bin/java | grep -v grep
      changed_when: False
