---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - set_fact:
        wfly_http_port: 8080

    - wait_for:
        port: "{{ wfly_http_port }}"

    - name: "Check if web connector is accessible"
      uri:
        url: "http://localhost:{{ wfly_http_port }}/"
        return_content: yes

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check if service is started
      assert:
        that:
          - ansible_facts is defined
          - ansible_facts.services is defined
          - ansible_facts.services['tomcat.service'] is defined
          - ansible_facts.services['tomcat.service']['state'] is defined
          - ansible_facts.services["tomcat.service"]['state'] == 'running'
