---
- name: Validate credentials
  ansible.builtin.assert:
    that:
      - (rhn_username is defined and eap_enable is defined and eap_enable) or not eap_enable is defined or not eap_enable or eap_offline_install
      - (rhn_password is defined and eap_enable is defined and eap_enable) or not eap_enable is defined or not eap_enable or eap_offline_install
    quiet: True
    fail_msg: "Cannot install Red Hat Enterprise Application Platform without RHN credentials. Define rhn_username and rhn_password are defined or set eap_offline_install"

- name: "Check that required packages list has been provided."
  ansible.builtin.assert:
    that:
      - wildfly_prereqs_packages is defined
    quiet: true
    fail_msg: "Required packages list was not defined"

- name: "Prepare packages list"
  ansible.builtin.set_fact:
    wildfly_packages_list: "{{ wildfly_prereqs_packages }}"
  when:
    - not wildfly_install is defined
    - not wildfly_install.java.package_name is defined

- name: "Add JDK package {{ wildfly_install.java.package_name }} to packages list"
  ansible.builtin.set_fact:
    wildfly_packages_list: "{{ wildfly_prereqs_packages + [ wildfly_install.java.package_name ] }}"
  when:
    - wildfly_install.java is defined
    - wildfly_install.java.package_name is defined

- name: "Install required packages ({{ wildfly_packages_list | length }})"
  ansible.builtin.package:
    name: "{{ wildfly_packages_list }}"
    state: present
  become: yes
  when:
    - wildfly_packages_list | length > 0
    - not wildfly_install_skip_prereqs is defined
