---
- name: Retrieve PIDFile value
  ansible.builtin.systemd:
    name: "{{ wildfly_instance_name }}"
  register: pidfile_value
  changed_when: false #Only reading properties, not doing any changes.

- name: "Notifying handlers to reload {{ wildfly_instance_name }}, if the PID path changed"
  ansible.builtin.debug:
    msg: "Reload {{ wildfly_instance_name }} if the systemd config got changed"
  when: pidfile_value.status.PIDFile != wildfly_systemd.selinux.pid_path + '/' + wildfly_instance_name + '.pid'
  notify:
    - Perform daemon-reload
