---
- assert:
    that:
      - instance_name is defined
    quiet: true

- block:
  - name: "Stop Wildfly instance {{ instance_name }}"
    service:
      name: "{{ instance_name }}"
      state: stopped
  rescue:
    - debug:
        msg: "Service {{ instance_name }} has already been removed."
