---
- name: Verify
  hosts: instance
  vars_files:
    - vars.yml
  collections:
    - middleware_automation.wildfly
  tasks:
    - name: "Verify only if scenario is running upstream"
      block:
        - name: "Include apps verification"
          ansible.builtin.include_tasks: ../verify_apps.yml
          when:
            - wildfly_apps is defined and wildfly_apps | length > 0

        - name: "STEP 1: Add the 'test' system property (The Action)"
          ansible.builtin.include_role:
            name: wildfly_utils
            tasks_from: jboss_cli.yml
          vars:
            jboss_cli_query: "/system-property=test:add(value=testvalue)"

        - name: "STEP 2: Verify the property using wildfly_validation_queries (The Validation)"
          ansible.builtin.include_role:
            name: wildfly_validation
          vars:
            wildfly_validation_queries:
              - { 
                  query: '/system-property=test:read-attribute(name=value)', 
                  expected_result: 'testvalue', 
                  expected_result_undefined: False
                }
      when:
        - not eap_enable is defined
