---
- name: Check installation
  ansible.builtin.assert:
    that:
      - eap_enable is defined and eap_enable
    quiet: true
    fail_msg: "SSO (keycloak) adapter is only available on Red Hat EAP installations."

- name: Check arguments
  ansible.builtin.assert:
    that:
      - rhn_sso_adapter_v is defined
      - wildfly_offline_install or rhn_cp_id is defined
      - wildfly_offline_install or (rhn_username is defined and rhn_password is defined)
      - wildfly_home is defined
    quiet: true
    fail_msg: "One or more required parameters for adapter installation are missing."

- name: Set adapter directory
  ansible.builtin.set_fact:
    patches_repository: "{{ override_patches_repository | default('/opt') }}"

- name: Set adapter filename
  ansible.builtin.set_fact:
    patch_filename: "{{ override_adapter_filename | default('rh-sso-' + rhn_sso_adapter_v + '-adapter-dist.zip') }}"

- name: Set adapter destination directory
  ansible.builtin.set_fact:
    path_to_patch: "{{ patches_repository }}/{{ patch_filename }}"

- name: Check download adapter archive path
  ansible.builtin.stat:
    path: "{{ path_to_patch }}"
  register: patch_archive_path

- name: Check local download archive path
  ansible.builtin.stat:
    path: "{{ lookup('env', 'PWD') }}"
  register: local_path
  delegate_to: localhost

- name: "Check downloaded archive: {{ patch_filename }}"
  ansible.builtin.stat:
    path: "{{ local_path.stat.path }}/{{ patch_filename }}"
  register: local_archive_path
  delegate_to: localhost

- name: "Download archive from RHN"
  ansible.builtin.include_tasks: tasks/download_from_rhn.yml
  vars:
    rhn_id_file: "{{ rhn_sso_adapter_id }}"
    zipfile_dest: "{{ path_to_patch }}"
  when:
    - not wildfly_offline_install
    - not local_archive_path.stat.exists

- name: Copy adapter archive to target nodes
  ansible.builtin.copy:
    src: "{{ local_path.stat.path }}/{{ patch_filename }}"
    dest: "{{ path_to_patch }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0640
  register: new_version_downloaded
  when:
    - not patch_archive_path.stat.exists
    - local_archive_path.stat is defined
    - local_archive_path.stat.exists
  become: yes

- name: Extract Adapter zipfile
  ansible.builtin.unarchive:
    src: "{{ path_to_patch }}"
    dest: "{{ wildfly_home }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    remote_src: yes
    creates: "{{ wildfly_home }}/modules/system/add-ons/keycloak"
  become: yes

- name: Perform installation
  block:
    - name: "Check service status, start for elytron if not running"
      block:
        - name: "Check if management interface is reachable"
          ansible.builtin.wait_for:
            host: "{{ jboss_cli_controller_host }}"
            port: "{{ jboss_cli_controller_port }}"
            timeout: 1
      rescue:
        - name: Set instance name
          ansible.builtin.set_fact:
            instance_name: "{{ wildfly_instance_name | default('wildfly') }}"
          when:
            - instance_name is not defined
        - name: "Deploy configuration"
          ansible.builtin.copy:
            src: "{{ wildfly_home }}/standalone/configuration/{{ wildfly_config_base }}"
            dest: "{{ wildfly_home }}/standalone/configuration/{{ instance_name }}.xml"
            group: "{{ wildfly_group }}"
            owner: "{{ wildfly_user }}"
            mode: 0640
            remote_src: true
            force: false
          become: yes
        - name: "Start wildfly for adapter installation"
          ansible.builtin.command: "{{ wildfly_home }}/bin/standalone.sh -c {{ instance_name }}.xml -Djboss.server.config.dir={{ wildfly_home }}/standalone/configuration/ -Djboss.server.base.dir={{ wildfly_home }}/standalone"
          changed_when: True
          async: 180
          poll: 0
          become: yes
          become_user: "{{ wildfly_user }}"
          register: adapter_install_process
        - name: "Wait for management interface is reachable"
          ansible.builtin.wait_for:
            host: "{{ jboss_cli_controller_host }}"
            port: "{{ jboss_cli_controller_port }}"
            timeout: 60
            delay: 10
            sleep: 5

    - name: Install adapter
      throttle: 1
      block:
        - name: "Check if Keycloak extension is already installed"
          ansible.builtin.include_tasks: jboss_cli.yml
          vars:
            jboss_home: "{{ wildfly_home }}"
            jboss_cli_query: "'/extension=org.keycloak.keycloak-adapter-subsystem:read-resource'"
            jboss_cli_timeout: 10
      rescue:
        - name: Install Keycloak Adapter and Reload
          block:
            - name: Install Keycloak Adapter
              ansible.builtin.include_tasks: jboss_cli.yml
              vars:
                jboss_home: "{{ wildfly_home }}"
                jboss_cli_file: "{{ wildfly_home }}/bin/adapter-elytron-install.cli"
                jboss_cli_timeout: 10
            - name: Reload After Keycloak Adapter Install
              ansible.builtin.include_tasks: jboss_cli.yml
              vars:
                jboss_home: "{{ wildfly_home }}"
                jboss_cli_query: ":reload"
                jboss_cli_timeout: 60
              when: "'process-state: reload-required' in cli_result.stdout"

    - name: "Stop service if it was started for adapter install"
      ansible.builtin.include_tasks: jboss_cli.yml
      vars:
        jboss_home: "{{ wildfly_home }}"
        jboss_cli_query: "'shutdown'"
        jboss_cli_timeout: 60
      when:
        - adapter_install_process is defined
        - not eap_no_restart_after_patch
        - cli_result.rc == 0
