---
- import_playbook: ../prepare.yml

- name: "Retrieve webapp"
  hosts: all
  vars:
    path_to_app: /tmp/info.war
    download_app_url: 'https://drive.google.com/uc?export=download&id=13K7RCqccgH4zAU1RfOjYMehNaHB0A3Iq'
  tasks:
    - name: "Deploy webapp"
      ansible.builtin.get_url:
        url: "{{ download_app_url }}"
        dest: "{{ path_to_app }}"
