---
- name: Playbook to install Wildfly using Prospero
  hosts: localhost
  vars:
    wildfly_install_use_prospero: True
  collections:
    - middleware_automation.wildfly
  tasks:

    - name: "Install server using Prospero"
      ansible.builtin.include_role:
        name: wildfly_install

    - name: "Run server with systemd"
      ansible.builtin.include_role:
        name: wildfly_systemd
